config/routes.rb
BrainTrade::Application.routes.draw do
  
  get 'login' => 'sessions#new', :as => "new_session"
  post 'login' => 'sessions#create', :as => "login_sessions"
  get 'logout' => 'sessions#destroy', :as => "logout_sessions"
  match 'auth/:provider/callback', to: 'sessions#createoauth', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]

  resources :users
 
  resources :categories, only: [:index, :show]
  resources :subjects, only: [:show]
  resources :offerings
  resources :meetups, except: [:index, :destroy]

  root to: "sessions#index"

  

end

app/models/offering.rb
class Offering < ActiveRecord::Base
  belongs_to :teacher, class_name: "User"
  has_many :meetups
  belongs_to :subject

  attr_accessible :teacher_id, :hangout, :location, :subject_id, :details

  attr_accessor :in_person, :category

end

app/controllers/offerings_controller.rb
class OfferingsController < ApplicationController

  skip_before_action :require_login, except: [:create, :update]
  skip_before_action :warn_not_logged_in, except: [:new, :edit]

  def index
    @offerings = Offering.all
  end

  def show
    @offering = Offering.find_by_id(params[:id])
  end

  def new
    @offering = Offering.new
    @category_names = []
    Category.all.each { |cat| @category_names << cat.name }
  end

  def create
    category = Category.find_by_name(params[:offering][:category])
    subject = category.subjects.find_by_name(params[:offering][:subject])
    if subject
      @offering = Offering.create(subject_id: subject.id,
                      teacher_id: current_user.id,
                      hangout: params[:offering][:hangout],
                      location: params[:offering][:location],
                      details: params[:offering][:details])
    else
      subject = category.subjects.create(name: params[:offering][:subject])
      @offering = Offering.create(subject_id: subject.id,
                      teacher_id: current_user.id,
                      hangout: params[:offering][:hangout],
                      location: params[:offering][:location],
                      details: params[:offering][:details])
    end
    
    if @offering
      redirect_to offering_path(@offering)
    else
      flash.now[:error] = 'Offering not created'
      render new_offering_path
    end
  end

  def edit
    @offering = Offering.find(params[:id])
    @category_names = []
    Category.all.each { |cat| @category_names << cat.name }
  end

  def update
    @offering = Offering.find(params[:id])
    category = Category.find_by_name(params[:offering][:category])
    subject = category.subjects.find_by_name(params[:offering][:subject])
    if subject
      updated = @offering.update(subject_id: subject.id,
                      hangout: params[:offering][:hangout],
                      location: params[:offering][:location],
                      details: params[:offering][:details])
    else
      subject = category.subjects.create(name: params[:offering][:subject])
      updated = @offering.update(subject_id: subject.id,
                      hangout: params[:offering][:hangout],
                      location: params[:offering][:location],
                      details: params[:offering][:details])
    end
    if updated
      flash[:success] = 'Offering Updated'
      redirect_to offering_path(@offering)
    else
      flash.now[:error] = 'Offering not Updated'
      render new_offering_path
    end
  end
end

app/views/offerings/edit.html.erb
<h1>Edit your teaching offering</h1>

<!-- Subject:
Hangout? (Y/N)
In person? 
(If yes, show location)
Location:
More details: (Your background in this subject, etc.) -->

<%= form_for @offering, url: {action: "update"} do |f| %>
  
  <%= f.label :category %>
  <%= f.select :category, @category_names, :selected => @offering.subject.category.name %>

  <%= f.label :subject %>
  <%= f.text_field :subject, :value => @offering.subject.name %>

  <%= f.label :hangout %>
  <%= f.check_box :hangout %>

  <%= f.label :in_person %>
  <%= f.check_box :in_person %>


  <!-- for v 1.1 will add AJAX so this field
  only appears if in-person box is checked -->
  <%= f.label :location %> 
  <%= f.text_field :location %>

  <%= f.label :details %>
  <%= f.text_area :details %>

  <br>

  <%= f.submit "Update" %>
    <div class="edit_button"><%= link_to "Cancel", offering_path(@offering.id) %></div><br>

<% end %>

app/views/offerings/index.html.erb
<h1>All offerings on this site</h1>
<% @offerings.each do |offering| %>
  <ul class="list-group">
    <li class="list-group-item"><a href="/offerings/<%=offering.id%>"><%= offering.subject.name %> by <%= User.find_by_id(offering.teacher_id).first_name %></a></li>
  </ul>
<% end %>

app/views/offerings/new.html.erb
<h1>Create a new teaching offering</h1>

<!-- Subject:
Hangout? (Y/N)
In person? 
(If yes, show location)
Location:
More details: (Your background in this subject, etc.) -->

<%= form_for @offering, url: {action: "create"} do |f| %>
  
  <%= f.label :category %>
  <%= f.select :category, @category_names %>

  <%= f.label :subject %>
  <%= f.text_field :subject %>

  <div>Please choose your availability type...</div>

  <div><label class="hangout_check_box">
    <%= f.label :hangout, :class => "checkbox inline" %>
    <%= f.check_box :hangout %><br>
  </label></div>



  <div class"in_person_check_box">
    <%= f.label :in_person, :class => "checkbox inline" %>
    <%= f.check_box :in_person %><br><br>
  </div>

  <!-- for v 1.1 will add AJAX so this field
  only appears if in-person box is checked -->
  <%= f.label :location %> 
  <%= f.text_field :location %>

  <%= f.label :details %>
  <%= f.text_area :details %>
  <br>

  <%= f.submit "Create" %>
<% end %>

app/views/offerings/show.html.erb
<h1 class="learn_from"> Learn <%= @offering.subject.name %> from <%= @offering.teacher.first_name %> <img class="img-circle"<%= gravatar_for @offering.teacher %></h1>



<div class="meetup_place">
  <% if @offering.hangout %>
    <h4> <i class="icon-facetime-video"></i>  Available via Google hangouts</h4>
  <% end %>

  <% if @offering.location != '' %>
    <h4><i class="icon-map-marker"></i>  Available in person at: <%= @offering.location %></h4>


    <%= render "shared/maps"%>

  <% end %>

  <div class="expertise_description">
    <h3> <%= @offering.teacher.first_name %>'s experience with <%= @offering.subject.name %>:</h3>
    <div class="expertise_details"><%= @offering.details %></div>
  </div>
<div>

<!-- <h3>Rankings would go here</h3>
<h3>Show up rate would go here</h3>
<h3>Reviews would go here</h3> -->

<br>
<!-- <button>Learn <%= @offering.subject.name %> from <%= @offering.teacher.first_name %></button> -->

<div><%#= link_to "Learn #{@offering.subject.name} from #{@offering.teacher.first_name}", meetups_path %></div>



<% if @offering.teacher_id == session[:user_id] %>

  <div class="edit_button btn btn-large btn-primary"><%= link_to "Edit Offering", edit_offering_path %></div><br>
  
<% else %>

  <%= "Learn #{@offering.subject.name} from #{@offering.teacher.first_name}" %>

	<% if @offering.hangout %>
    <%= button_to "Via Google Hangouts", controller: 'meetups', action: "create", :"data-offering_id" => @offering.id, :"data-method" => 'hangout' %>
  <% end %>

  <% if @offering.location != '' %>
    <%= button_to "In Person", controller: 'meetups', action: "create", :"data-offering_id" => @offering.id, :"data-method" => 'in-person' %>
  <% end %>

<% end %>






  