config/routes.rb
BrainTrade::Application.routes.draw do
  
  get 'login' => 'sessions#new', :as => "new_session"
  post 'login' => 'sessions#create', :as => "login_sessions"
  get 'logout' => 'sessions#destroy', :as => "logout_sessions"
  match 'auth/:provider/callback', to: 'sessions#createoauth', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]

  resources :users
 
  resources :categories, only: [:index, :show]
  resources :subjects, only: [:show]
  resources :offerings
  resources :meetups, except: [:index, :destroy]

  root to: "sessions#index"

  

end

app/models/user.rb
class User < ActiveRecord::Base

  attr_accessible :first_name, :last_name, :email, :password, :password_confirmation, :bio

  has_many :ratings, foreign_key: :learner_id
  has_many :learning_meetups, class_name: "Meetup", foreign_key: :learner_id
  has_many :offerings, foreign_key: :teacher_id
  has_many :teaching_meetups, through: :offerings, source: :meetups

  # VALIDATIONS
  validates_presence_of :first_name, :last_name, :email, :password, :on => :create
  validates_uniqueness_of :email
  validates :email, format: {with: /.+@.{2,}\.[a-zA-Z]{2,6}/, message: "- must be a valid format"}
  validates :password, length: { in: 6..20, message: "- must be between 6 and 20 characters" }, on: :create
  
  has_secure_password 

  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
      user.first_name = auth.info.first_name
      user.last_name = auth.info.last_name
      user.username = auth.info.name
      user.email = auth.info.email
      user.provider = auth.provider
      user.uid = auth.uid.to_i
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.password = "password"
      user.password_confirmation = "password"
      if user.oauth_expires_at!=nil
        user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      end
      if User.find_by_email(user.email)
        user.name = "exists" 
      else
        user.name = nil 
        user.credit += 1
      end
      user.save!
    end
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include ApplicationHelper

  skip_before_action :require_login, except: [:update]
  skip_before_action :warn_not_logged_in

  def index
   @users = User.all
  end

  def create
    #create account
    p params
    @user = User.new(params[:user])
    #respond_to do |format|
      if @user.save
        session[:user_id] = @user.id
        @user.credit += 1
        @user.save
        flash[:success] = "By Joining BrainTrade you have earned one free credit toward learning."
        UserMailer.welcome_email(@user).deliver
        #format.json { render json: @user, status: :created, location: @user }
        redirect_to user_path(@user)
        #format.html { redirect_to(@user, notice: 'User was successfully created.') }
      else
         flash[:error] = @user.errors.full_messages
         redirect_to new_user_path
      end
     #end
  end

  def new
    #Account creation form
    @user = User.new
  end

  def edit
    #edit profile page form
      @user = User.find(session[:user_id])
      if request.xhr?
          render :edit, layout: false
      end                
  end


  def update
    #update profile
    @user = User.find(session[:user_id])
    if @user.update_attributes(params[:user])
        flash[:success] = "Your info has been updated!"
        redirect_to user_path(@user)
    else
        flash[:error] = "Your info has had a problem updating. Try again"
        render :edit
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def destroy
    User.destroy(session[:user_id])
    flash[:success] = "Your info has been deleted!"
    session[:user_id] = nil
    redirect_to(new_user_path)
  end

end

app/helpers/users_helper.rb
module UsersHelper
	def gravatar_for(user)
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		gravatar_url = "http://gravatar.com/avatar/#{gravatar_id}.png?s=180"
		image_tag(gravatar_url, alt: user.first_name, class: "gravatar")
	end

  def all_meetups_as_teacher
    Meetup.includes(:offering).where('offerings.teacher_id = ?', current_user.id).references(:offerings).all 
  end

  def all_meetups_as_student
    Meetup.where("learner_id = ?", current_user.id)
  end


  #As the teacher user profile...
  def awaiting_teacher_response_as_teacher
    not_accepted = []
    all_meetups_as_teacher.each do |meetup|
      if meetup.accepted != true
        not_accepted << meetup
      end
    end
    not_accepted
  end 


  def awaiting_student_response_as_teacher 
    not_confirmed = []
    all_meetups_as_teacher.each do |meetup|
      if meetup.accepted && meetup.date_time == nil
        not_confirmed << meetup
      end
    end
    not_confirmed
  end

  def confirmed_as_teacher  
    confirmed = []
    all_meetups_as_teacher.each do |meetup|
      if meetup.accepted && meetup.date_time?
        confirmed << meetup
      end
    end
    confirmed
  end



  #As the student user profile...
  def awaiting_teacher_response_as_student
    not_accepted = []
    all_meetups_as_student.each do |meetup|
      if meetup.accepted != true
        not_accepted << meetup
      end
    end
    not_accepted
  end

  def awaiting_student_response_as_student
    not_confirmed = []
    all_meetups_as_student.each do |meetup|
      if meetup.accepted && meetup.date_time == nil
        not_confirmed << meetup
      end
    end
    not_confirmed
  end

  def confirmed_as_student  
    confirmed = []
    all_meetups_as_student.each do |meetup|
      if meetup.accepted && meetup.date_time?
        confirmed << meetup
      end
    end
    confirmed
  end  


end

app/views/users/_student_meetup_list.html.erb
<div class="learning_requests">
  <div id="learn_title"><h3>My learning requests:</h3></div>

  <h4>Teachers I would like to learn from...</h4>
    <ul>
      <% awaiting_teacher_response_as_student.each do |meetup| %>
        <li><%= link_to "#{meetup.offering.subject.name} with #{meetup.offering.teacher.first_name}", meetup_path(meetup) %></il>
      <% end %>
    </ul>

  <h4>Teachers awaiting my scheduling response...</h4>

    <ul>
      <% awaiting_student_response_as_student.each do |meetup| %>
        <li><%= link_to "#{meetup.offering.subject.name} with #{meetup.offering.teacher.first_name}", edit_meetup_path(meetup) %></il>
      <% end %>
    </ul>


  <h4>Teachers I'm scheduled to learn from...</h4>

    <ul>
      <% confirmed_as_student.each do |meetup| %>
      <% if meetup.cancelled == nil %>
        <li><%= link_to "#{meetup.offering.subject.name} with #{meetup.offering.teacher.first_name}", meetup_path(meetup) %></il>
          <% end %>
      <% end %>
    </ul>

    <h4>Cancelled Appointments</h4>

    <ul>
      <% confirmed_as_student.each do |meetup| %>
      <% if meetup.cancelled == true %>
        <li><%= link_to "#{meetup.offering.subject.name} with #{meetup.offering.teacher.first_name}", meetup_path(meetup) %></il>
      <% end %>
      <% end %>
    </ul>
</div>

app/views/users/_teacher_meetup_list.html.erb
<div class="teaching_requests">

  <div id="teach_title xxtest"><h3 id='teach_title'>My teaching requests:</h3></div>

  <h4>Students who would like to learn from me...</h4>
    <ul>
      <% awaiting_teacher_response_as_teacher.each do |meetup| %>
        <li><%= link_to "#{meetup.offering.subject.name} with #{meetup.learner.first_name}", edit_meetup_path(meetup) %></il>
      <% end %>
    </ul>

  <h4>Pending scheduling response from student...</h4>
    <ul>
      <% awaiting_student_response_as_teacher.each do |meetup| %>
        <li><%= link_to "#{meetup.offering.subject.name} with #{meetup.learner.first_name}", meetup_path(meetup) %></il>
      <% end %>
    </ul>

  <h4>Students I'm scheduled to teach...</h4>

    <ul>
      <% confirmed_as_teacher.each do |meetup| %>
      <% if meetup.cancelled == nil %>
        <li><%= link_to "#{meetup.offering.subject.name} with #{meetup.learner.first_name}", meetup_path(meetup) %></il>
          <% end%>
      <% end %>
    </ul>

    <h4>Cancelled Appointments</h4>

    <ul>
      <% confirmed_as_teacher.each do |meetup| %>
      <% if meetup.cancelled == true %>
        <li><%= link_to "#{meetup.offering.subject.name} with #{meetup.learner.first_name}", meetup_path(meetup) %></il>
      <% end %>
      <% end %>
    </ul>
</div>

app/views/users/edit.html.erb
  <%= form_for @user do |user| %>
    <div id="profile_info">
      <%= user.label :first_name %>
      <%= user.text_field :first_name  %>
    </div>
     <div id="profile_info">
      <%= user.label :last_name %>
      <%= user.text_field :last_name  %>
    </div>

    <div id="profile_info">
      <%= user.label :email %>
      <%= user.text_field :email  %>
    </div>

    <div id="profile_info">
      <%= user.label :bio %>
      <%= user.text_area :bio, cols: 30, rows: 10%>
    </div>

    <div id="profile_info">
      <%= user.label :password %>
      <%= user.password_field :password  %>
    </div id="profile_info">
    <div>
      <%= user.label :password_confirmation %>
      <%= user.password_field :password_confirmation  %>
    </div>
    
    <%= user.submit %>

  <% end %>

app/views/users/index.html.erb
<h1>All users of Braintrade</h1>
<ul>
<% @users.each do |user| %>
	    <li><a href="/users/<%=user.id%>"><%= user.first_name %></a></li>
<% end %>
</ul>

app/views/users/new.html.erb
<div class="container">
        <%= form_for(@user) do |user| %>
            <h1>Create Account</h1>

                <!-- validations -->
   <!--                <% if @user.errors.any? %>
                      <div id="error_explanation">
                        <h2><%= pluralize(@user.errors.count, "error") %> prohibited this post from being saved: </h2>

                        <ul>
                          <% @user.errors.full_messages.each do |msg| %>
                          <li><%= msg %></li>
                          <% end %>
                        </ul>
                      </div>
                      <% end %> -->
            <!-- Create an Account form -->
            <div>
                <%= user.label :first_name %>
                <%= user.text_field :first_name  %>
            </div>
            
            <div>
                <%= user.label :last_name %>
                <%= user.text_field :last_name  %>
            </div>
            
            <div>
                <%= user.label :email %>
                <%= user.text_field :email  %>
            </div>

            <div>
                <%= user.label :password %>
                <%= user.password_field :password %>
            </div>
            <div>
                <%= user.label :password_confirmation %>
                <%= user.password_field :password_confirmation  %>
            </div>
                <%= user.submit "Create User" %>

        <% end %>
        <a class="zocial googleplus" href="/auth/google_oauth2">Sign in with Google</a>

</div>

<div class="container">

        <!-- Login form -->
        <h1>Login</h1>

        <%=form_tag login_sessions_path do %>
        <div>
            <%= label_tag :email %>
            <%= text_field_tag :email, nil, id: "login_email" %><br>
        </div>
        <div>
            <%= label_tag :password %>
            <%= password_field_tag :password,  nil, id: "login_password" %><br>
        </div>
            <%= submit_tag  nil, id: "login_user" %>
        <% end %>

</div>

app/views/users/show.html.erb
<div class= "top_container">

    <div class="picture_container">
        <% provide(:title, @user.first_name) %>
        <h1><%= gravatar_for @user %></h1>
        <div id="credits" class="btn btn-large disabled" href="#"><i class="icon-star"></i> Credits: <%= @user.credit  %></div>
        <br><br>
        <div class="teaching_button">
          <a class="btn" href="/offerings/new">
            <i class="fa fa-flag fa-2x pull-left"></i><i class="icon-leaf"></i></i> Teach Something New!</a>
      
        <div class="edit_button_profile"><%= link_to "Edit", edit_user_path(current_user),:remote => true %></div>
         <br>
    </div id="delete"><%= link_to "Delete", "/users/delete", :method => :delete, :class => "btn btn-link", :confirm => "are you sure you want to delete your profile?" %>
        </div>
    </div>


    <div class="profile_info_container">
        <div class="profile_name"><h1><%= @user.first_name %></h1></div>
      <!-- <p id="profile_info"> Hi, My name is: <#%= @user.first_name %></p><br> -->
      <!-- <p id="profile_info"> Last name: <#%= @user.last_name %></p><br> -->
      <!-- <p id="profile_info"> Email: <#%= @user.email %></p><br> -->

    <div class="bottom_container">
    
    <div class="thigs_i_teach">
      <h3 id="teach_title">I teach:</h3>
        <ul id="subject_grouping"><% @user.offerings.each do |offering| %>
          <li id="teach_name"><%= link_to offering.subject.name, offering_path(offering) %></li>
          <% end %>
        </ul>
      <br><br>
      
    <div id="bio_info">Bio: <%= @user.bio %></div>
    </div>

    </div>
    <% if @user.id == current_user.id %>
        <%= render "teacher_meetup_list" %>
        <%= render "student_meetup_list" %>
       <br id="clear">
    <% end %>
<div>
      
  <br id="clear">
  
   

<!-- </div> -->