config/routes.rb
BrainTrade::Application.routes.draw do
  
  get 'login' => 'sessions#new', :as => "new_session"
  post 'login' => 'sessions#create', :as => "login_sessions"
  get 'logout' => 'sessions#destroy', :as => "logout_sessions"
  match 'auth/:provider/callback', to: 'sessions#createoauth', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]

  resources :users
 
  resources :categories, only: [:index, :show]
  resources :subjects, only: [:show]
  resources :offerings
  resources :meetups, except: [:index, :destroy]

  root to: "sessions#index"

  

end

app/views/shared/_maps.html.erb
  <head>
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no">
    <meta charset="utf-8">
    <title>Geocoding service</title>
    <style>
      html, body, #map-canvas {
        height: 100%;
        margin: 0px;
        padding: 0px
      }
      #panel {
        position: absolute;
        top: 5px;
        left: 50%;
        margin-left: -180px;
        z-index: 5;
        background-color: #fff;
        padding: 5px;
        border: 1px solid #999;
      }
    </style>
        <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false"></script>
    <script>
var geocoder;
var map;
function initialize() {
  geocoder = new google.maps.Geocoder();
  var latlng = new google.maps.LatLng(-34.397, 150.644);
  var mapOptions = {
    zoom: 8,
    // center: latlng
  }
  map = new google.maps.Map(document.getElementById('map-canvas'), mapOptions);
}

function codeAddress() {
  var address = document.getElementById('address').value;
  console.log(address)
  geocoder.geocode( { 'address': address}, function(results, status) {
    if (status == google.maps.GeocoderStatus.OK) {
      map.setCenter(results[0].geometry.location);
      var marker = new google.maps.Marker({
          map: map,
          position: results[0].geometry.location
      });
    } else {
      alert('Geocode was not successful for the following reason: ' + status);
    }
  });
}

google.maps.event.addDomListener(window, 'load', initialize);
  </script>


  </head>


<!-- Map div, shown if offering location has been set -->

  <div id="map-canvas" style="height:300px"></div>


<!-- More maps stuff, not sure if it matters where this goes -->
<input id="address" type="hidden" value="<%= @offering.location %>">
      <input type="hidden" value="Geocode" onclick="codeAddress()">

<script type="text/javascript">
  
  google.maps.event.addDomListener(window, 'load', codeAddress);
</script>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-fluid-top">
  <div class="navbar-inner">
    <div class="container-fluid">
      <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
       <%= link_to(image_tag("braintrade_logo_nav.png", :size => "25x25", :class => "brand"), root_path) %>
       <%= link_to "BrainTrade", root_path, {:class => "brand"}%>

      

      <div class="container-fluid nav-collapse">
        <ul class="nav">
           <li><%= link_to "Learn", categories_path %></li>
           <li><%= link_to "Teach", new_offering_path %></li>

           <!-- If user is signed in-->
                <% if current_user %>
                      <li><%= link_to "Logout", logout_sessions_path %></li>
                      <li><%= link_to "MyAccount", user_path(current_user) %></li>
                <% else %>
                      <li id="right"><%= link_to "Sign Up or Login", new_user_path %></li>
                      

                <% end %>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </div>
</div>

app/views/shared/_sidebar.html.erb
<div class="span3">
  <div class="well sidebar-nav">
    <ul class="nav nav-list">
      <li class="nav-header">Sidebar</li>
      <li><%= link_to "Link1", "/path1"  %></li>
      <li><%= link_to "Link2", "/path2"  %></li>
      <li><%= link_to "Link3", "/path3"  %></li>
    </ul>
  </div><!--/.well -->
</div><!--/span-->