config/routes.rb
BrainTrade::Application.routes.draw do
  
  get 'login' => 'sessions#new', :as => "new_session"
  post 'login' => 'sessions#create', :as => "login_sessions"
  get 'logout' => 'sessions#destroy', :as => "logout_sessions"
  match 'auth/:provider/callback', to: 'sessions#createoauth', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]

  resources :users
 
  resources :categories, only: [:index, :show]
  resources :subjects, only: [:show]
  resources :offerings
  resources :meetups, except: [:index, :destroy]

  root to: "sessions#index"

  

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :subjects

  attr_accessible :name

  def self.search(search)
    if search
      where 'name iLIKE ?', "%#{search}%"
    else
      scoped
    end
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  skip_before_action :require_login
  skip_before_action :warn_not_logged_in

  def index
    @categories = Category.search(params[:search])
    # @categories = Category.all
  end

  def show
    @category = Category.find_by_id(params[:id])

    if Subject.search(params[:search]).present?
      #@subjects = Subject.search(params[:search])#.find_by(category_id: @category.id)
      @subjects = Subject.search(params[:search]).where(:category_id => @category.id)
    else
      @subjects = @category.subjects.all
    end
  end

end

app/views/categories/index.html.erb
<h1>Browse Learning Categories</h1>
<br>

<%= form_tag(categories_path, method: "get") do %>
  <%= label_tag(:search, "") %>
  <%= text_field_tag(:search, params[:search], :placeholder => "Search by keyword") %>
  <%= submit_tag("Search", :name => nil, :class => "btn btn-primary search" ) %>
<% end %>

<div class ="wrapper">
<% @categories.each do |category| %>
  <ul class="well well-small">
    <a> <span class="badge badge-info"><%= category.subjects.all.count %></span>&nbsp&nbsp<%= link_to category.name, category_path(category.id), :class => "categories" %></a>
    
  </ul>
<% end %>
<br>
</div>

<!-- Bootstrap classes not working? Not sure why. -->

app/views/categories/show.html.erb
  <h1>Browse subjects in <%= @category.name %></h1>
  <br>
  <%= form_tag(category_path(@category.id), method: "get") do %>
  <%= label_tag(:search, "") %>
  <%= text_field_tag(:search, params[:search], :placeholder => "Search by keyword") %>
  <%= submit_tag("Search", :name => nil, :class => "btn btn-primary search" ) %>
<% end %>

  <div class="subjects_yay">
    <% @subjects.each do |subject| %>
      <ul class="well well-small">
        <a><span class="badge badge-success"><%= subject.offerings.all.count %></span>&nbsp&nbsp<%= link_to subject.name, subject_path(subject.id), remote: true, :class => "subjects" %></a>
      </ul>
           <div class="hide<%=subject.id%>" style="display:none;">
            <% subject.offerings.each do |offering| %>
              <ul class="list-group" >
                <li class="list-group-item" id="subjectid<%=subject.id%>">
                   <%= link_to offering_url(offering) do %>
                        <%= gravatar_for offering.teacher %>
                        <%= offering.teacher.first_name %>
                      <% end %>
                </li>
              </ul>
            <% end %>
          <br>
          </div>
    <% end %>
  </div> 
  